# Generated by Django 4.0.4 on 2022-08-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_category',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('CASHIER', 'Cashier')], max_length=100),
        ),
    ]
